ALTER TABLE dim_rule ADD COLUMN IF NOT EXISTS rule_name  VARCHAR(100);
ALTER TABLE dim_rule ADD COLUMN IF NOT EXISTS event_type VARCHAR(30);
ALTER TABLE dim_rule ADD COLUMN IF NOT EXISTS priority   SMALLINT;
ALTER TABLE dim_rule ADD COLUMN IF NOT EXISTS query_sql  TEXT;
