INSERT INTO dim_rule (rule_code, rule_name, event_type, priority, severity, blocks_operation, applies_rt, applies_nrt, is_active) VALUES
('RP01','challengeUsuarioDiferenteTitular',       'fullApplicationNRT', 1, 'LOW',    false, false, true,  false),
('RP02','challengeDosComprasMismoDia',             'fullApplicationNRT', 1, 'LOW',    false, false, true,  true),
('RP03','challengeMenos250a12cuotas',              'fullApplicationNRT', 1, 'LOW',    false, false, true,  true),
('RP04','challengeMas2500',                        'fullApplicationNRT', 1, 'LOW',    false, false, true,  true),
('RP05','challengeMasDosPagosenDia',               'fullApplicationNRT', 1, 'LOW',    false, false, true,  true),
('RP06','velocidad1h',                             'fullApplicationRT',  2, 'ALTO',   true,  true,  false, true),
('RP07','velocidad1d',                             'fullApplicationRT',  2, 'ALTO',   true,  true,  false, true),
('RP08','alerta3DSCVV6Horas',                      'fullApplicationRT',  3, 'ALTO',   false, true,  false, false),
('RP09','tresComprasDiferenteComercio1000PEN',     'fullApplicationRT',  5, 'ALTO',   false, true,  false, true),
('RP10','diferentesClientes365d',                  'fullApplicationRT',  2, 'ALTO',   true,  true,  false, true),
('RP11','blackListDNI',                            'fullApplicationRT',  2, 'ALTO',   true,  true,  false, true),
('RP12','whiteListDNI',                            'fullApplicationRT',  1, 'LOW',    false, true,  false, true),
('RP13','blackListCard',                           'fullApplicationRT',  2, 'ALTO',   true,  true,  false, true),
('RP14','whiteListCard',                           'fullApplicationRT',  2, 'LOW',    false, true,  false, true),
('RP15','blackListMail',                           'fullApplicationRT',  2, 'ALTO',   true,  true,  false, true),
('RP16','whiteListMail',                           'fullApplicationRT',  2, 'LOW',    false, true,  false, true),
('RP17','blackListUserDNI',                        'fullApplicationRT',  2, 'LOW',    true,  true,  false, true),
('RP18','whiteListUserDNI',                        'fullApplicationRT',  2, 'LOW',    false, true,  false, true),
('RP19','challengDobleTicketPromedioComercio',     'fullApplicationRT',  5, 'ALTO',   false, true,  false, true),
('RP20','challengeDosComprasMismoDiasRiesgoAlto',  'fullApplicationRT',  3, 'ALTO',   false, true,  false, true),
('RP21','challengeTresComprasMismoDiasRiesgoAlto', 'fullApplicationRT',  3, 'ALTO',   false, true,  false, true),
('RP22','challengeCuatroComprasTresDiasRiesgoAlto','fullApplicationRT',  3, 'ALTO',   false, true,  false, true),
('RP23','challengeCompraPreviaMenor12cuotas',      'fullApplicationRT',  7, 'MEDIO',  false, true,  false, true),
('RP24','challengeCreditoPagadoPreviamente',       'fullApplicationRT',  7, 'MEDIO',  false, true,  false, true),
('RP25','challengeUsuarioDiferenteTitularRiesgoAlto','fullApplicationRT',7, 'MEDIO',  false, true,  false, true),
('RP26','challengeCorreoRiesgoAlto',               'fullApplicationRT',  5, 'ALTO',   false, true,  false, true),
('RP27','challengeMayorEdad',                      'fullApplicationRT',  3, 'ALTO',   false, true,  false, true),
('RP28','challengeInStoreFueraHorario',            'fullApplicationRT',  6, 'ALTO',   false, true,  false, true),
('RP29','departamentoInStore24h',                  'fullApplicationRT',  6, 'ALTO',   true,  true,  false, true),
('RP30','departamentoInStoreDiferente',            'fullApplicationRT',  2, 'MEDIO',  true,  true,  false, false),
('RP31','validacionFallecido',                     'fullApplicationRT',  2, 'ALTO',   true,  true,  false, true),
('RP32','blackListMobilePhone',                    'fullApplicationRT',  2, 'LOW',    true,  true,  false, true),
('RP33','challengeCambioDeNumero',                 'fullApplicationRT',  7, 'MEDIO',  false, true,  false, true),
('RP34','challengeDobleComprasComercio',           'fullApplicationRT',  3, 'MEDIO',  false, true,  false, true),
('RP35','challengeMas500a12cuotas',                'fullApplicationRT',  1, 'LOW',    false, true,  false, true)
ON CONFLICT (rule_code) DO NOTHING;